authors: []
blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DPYTHON_EXECUTABLE=/home/crescentrose/anaconda3/envs/sfm/bin/python3
- -DPYTHON_INCLUDE_DIR=/home/crescentrose/anaconda3/envs/sfm/include/python3.8
- -DPYTHON_LIBRARY=/home/crescentrose/anaconda3/envs/sfm/lib/libpython3.so
devel_layout: linked
devel_space: devel
extend_path: null
extends: null
install: true
install_space: install
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
